### ISSUE TITLE
Old package version in AUR

### ISSUE THREAD

**Issue by ruffson** [ros-melodic-arch/ros-melodic-angles#3]
This [package in AUR](https://aur.archlinux.org/packages/ros-melodic-angles/) is still on the old version `1.9.11-2`.
What is the process of syncing this package to the AUR?

**Comment by acxz** [comment]
@ruffson sorry for the late response, but we have shifted our development and maintenance over at [ros-noetic-arch](https://github.com/ros-noetic-arch)

**Comment by fmauch** [comment]
In fact, the version inside this repo is too new. The [rosdistro entry](https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml#L162) links to version `1.9.12`, while the master branch of this repo is at version `1.9.13`.

**Comment by bionade24** [comment]
That's a thing we should obey more. Our updating scripts with rosdistro works fine and maybe we shouldn take update PRs at all, only bugfixes.

**Comment by ruffson** [comment]
Sorry about that. I guess I used a too new version of `ros_controllers` which required the new `shortest_angular_distance_with_large_limits`. I thought it was enough to pull the `ros_controllers` `melodic` branch but I guess I should've used the release branch. Apologies!

**Comment by bionade24** [comment]
> Sorry about that. I guess I used a too new version of `ros_controllers` which required the new `shortest_angular_distance_with_large_limits`. I thought it was enough to pull the `ros_controllers` `melodic` branch but I guess I should've used the release branch. Apologies!

One thing I quite don't understand is why every ros user here seems to want to get every special or new package into here. Why not load them + deps into your workspace with `wstool` or with git directly. Done in 5 minutes and then hide the package.

**Comment by fmauch** [comment]
I can only speak for myself, but I have many different workspaces that I share with colleagues using wstool. Therefor, I like to keep things clean in my workspaces to only contain the packages that can't be installed through the binary repo. Otherwise we could skip this whole things and use complete from-src builds anyway....

**Comment by ruffson** [comment]
> > Sorry about that. I guess I used a too new version of `ros_controllers` which required the new `shortest_angular_distance_with_large_limits`. I thought it was enough to pull the `ros_controllers` `melodic` branch but I guess I should've used the release branch. Apologies!
> 
> One thing I quite don't understand is why every ros user here seems to want to get every special or new package into here. Why not load them + deps into your workspace with `wstool` or with git directly. Done in 5 minutes and then hide the package.

I did clone `ros_controllers` into a local workspace and managed it with wstool among a bunch of other repos. And it's `melodic-devel` branch required that newer version from this repo. I don't know what other users do or why this is relevant here though.

**Comment by bionade24** [comment]
The "problem" I have is that people are creating packages like ros-melodic-very-special-sdk that are barely used by more than 2 people. Then they switch back to LXC container with Ubuntu for some reason and I spent my patching them because they failed in the CI.

> I can only speak for myself, but I have many different workspaces that I share with colleagues using wstool. Therefor, I like to keep things clean in my workspaces to only contain the packages that can't be installed through the binary repo. Otherwise we could skip this whole things and use complete from-src builds anyway....

This is a case I wasn't aware of.  Although I had this feeling, we never declined any package request, but sometimes during patching it just felt like wasting time when you know the package is outdated/broken for > 3 months and no one complained.

**Comment by acxz** [comment]
Maybe just have a blacklist in your CI?
In arch4edu, if it doesn't build it just stays stagnant until someone comes along and complains/fixes the package and then the CI picks back up again.
idk feels more like a CI issue to me.

I think any package that is in the official ros buildfarm qualifies for us to package and create it, but in terms of patching and maintaining it. That's just on whoever wants to ensure that it works for Arch.
At least thats my take on it.

I understand having all packages in this repo building properly is nice, but I think that is just too much work for ~2 people.

> wasting time when you know the package is outdated/broken for > 3 months and no one complained.

I feel this very much ;(

**Comment by bionade24** [comment]
> Maybe just have a blacklist in your CI?
> In arch4edu, if it doesn't build it just stays stagnant until someone comes along and complains/fixes the package and then the CI picks back up again.
> idk feels more like a CI issue to me.

Can't bc I currently don't check if deps are available outside bc it runs on a debian server obviously without pacman to check this. But I wanted to improve this situation and drone or any other CI didn't fitted the thing I really wanted so I just started now to write my own more generic ABS CI/CD with an webinterface.
